function [gNBPluto,UEPluto] = initPlutoSDR(pRadioIDTx,pRadioIDRx,pCenterFrequency,pGain,rxLength,gNB,UE)
%INITPLUTO Summary of this function goes here
%   Detailed explanation goes here
% Create a tx pluto object
load plutoTxFilter
UEPluto = sdrtx('Pluto','RadioID',pRadioIDTx,...
          'CenterFrequency',pCenterFrequency, ...
          'BasebandSampleRate',gNB.cSampleRate,'Gain',pGain,...
          'ShowAdvancedProperties',true,...
          'UseCustomFilter',true,filtTxConfig{:});

resetPluto(UEPluto,1);

% UEPluto = sdrtx('Pluto','RadioID',pRadioIDTx,...
%           'CenterFrequency',pCenterFrequency, ...
%           'BasebandSampleRate',gNB.cSampleRate,'Gain',pGain,...
%           'ShowAdvancedProperties',true...
%           );

% Create a rx pluto object
load plutoRxFilter
gNBPluto = sdrrx('Pluto',...
       'RadioID',pRadioIDRx,...
       'CenterFrequency',pCenterFrequency,...
       'BasebandSampleRate',UE.cSampleRate,...
       'SamplesPerFrame', 2*rxLength,...
       'OutputDataType','double',...
       'UseCustomFilter',true,filtRxConfig{:}); 
resetPluto(gNBPluto,1);

gNBPluto.GainSource = 'Manual';
%gNBPluto.Gain = 57;        % Use this for 2GHz
gNBPluto.Gain = 47;         % Use this for 2.4 GHz

% gNBPluto = sdrrx('Pluto',...
%        'RadioID',pRadioIDRx,...
%        'CenterFrequency',pCenterFrequency,...
%        'BasebandSampleRate',UE.cSampleRate,...
%        'SamplesPerFrame', 2*rxLength,...
%        'OutputDataType','double'); 
end

